### ISSUE TITLE
Real-world problems & Seed

### ISSUE THREAD

**Issue by MartinKavik** [fattenap/react-autolayout#2]
@fattenap 
Hi, I was thinking about something similar for Seed some months ago - a combination of writing / recording layout constraints or expected behaviors for values (extra/inter)polation in GUI designer or text IDE.

What problems did you encounter while writing / using this lib?
I can imagine that JS was slow for more complex websites or it makes almost impossible to prerender website / use SSR because of not using CSS; or something else?

**Comment by fattenap** [comment]
This lib was just a wrapper around [AutoLayout.js](https://github.com/ijzerenhein/autolayout.js/). You should check it out. It explains the Visual Format Language (VFL), which is the syntax that is used. And yes, you are right. The javascript was the major bottle neck, especially as the application/UI got more complex. I wasn't really thinking too much about SSR back then, but yes it wouldn't have been possible. There was also a reluctance, by web devs, to use something different. Which I can appreciate. The syntax (VFL) could get hard to maintain also.

But I think there is definitely a benefit in separating layout from styling.
